### ISSUE TITLE
Path traversal vulnerability

### ISSUE THREAD

**Issue by Contrabass26** [H-26/Personal-Website#1]
The website appears to be succeptible to a path traversal attack. Obviously I would never hack anything, but as an example I am able to access [this file](https://josephhenderson.me/error.log). A more experienced attacker could potentially access files that they know are present - e.g. macOS system files. This is probably not good.

**Comment by H-26** [comment]
The website is hosted on GitHub pages, so you shouldn't be able to access any files outside of that folder (at least not my files). I've reviewed the file in question and it was an error log from a previous bootstrap studio export. As it doesn't include any sensitive data it is not urgent. Therefore, I will review the rest of the files and remove any that are unnecessary in the next commit. Thanks!
